name: world-finals2019

default-extensions:
- BlockArguments
- LambdaCase
- OverloadedStrings
- TypeApplications
- ViewPatterns

dependencies:
- base
- containers
- extra
- safe
- vector

library:
  source-dirs: src

executables:
  beautiful-bridges:
    main:                Main.hs
    source-dirs:         app/BeautifulBridges
    dependencies:
      - world-finals2019

  circular-dna:
    main:                Main.hs
    source-dirs:         app/CircularDNA
    dependencies:
      - world-finals2019

  traffic-blights:
    main:                Main.hs
    source-dirs:         app/TrafficBlights
    dependencies:
      - world-finals2019
