name: world-finals2019

default-extensions:
- BlockArguments
- FlexibleContexts
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- TupleSections
- TypeApplications
- ViewPatterns

dependencies:
- array
- base
- containers
- extra
- safe
- vector
- vector-algorithms

library:
  source-dirs: src

executables:
  beautiful-bridges:
    main:                Main.hs
    source-dirs:         app/BeautifulBridges
    dependencies:
      - world-finals2019

  circular-dna:
    main:                Main.hs
    source-dirs:         app/CircularDNA
    dependencies:
      - world-finals2019

  first-of-her-name:
    main:                Main.hs
    source-dirs:         app/FirstOfHerName
    dependencies:
      - world-finals2019

  traffic-blights:
    main:                Main.hs
    source-dirs:         app/TrafficBlights
    dependencies:
      - world-finals2019
